{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microshield-bpo.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "microshield-bpo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.data }}
  {{- toYaml .Values.secret.data | nindent 2 }}
  {{- else }}
  placeholder: ""
  {{- end }}
{{- end }}
